### ISSUE TITLE
Courses DISCUSSION FORUM : under 1200px, the texte goes over buttons

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#14]
http://rue89-theme2.sandbox.opencraft.com/courses/course-v1:TestX+TST-2+now/discussion/forum/i4x-PREPROD-3-course-2015/threads/55f97f7cb335bd7435000001

![capture d ecran 2015-09-24 a 16 19 06](https://cloud.githubusercontent.com/assets/3848536/10075388/c102a9dc-62d5-11e5-9a74-60ee97cfc1aa.png)
![capture d ecran 2015-09-24 a 16 19 13](https://cloud.githubusercontent.com/assets/3848536/10075387/c1011874-62d5-11e5-83fc-5b1bd560b693.png)

**Comment by mperrien** [comment]
Fixed.
