### ISSUE TITLE
Courses DISCUSSION FORUM : Dropdown menu "toutes les..." : add rollOver effect over subitems

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#15]
RollOver underline on all sub-items : 
- Toutes les discussions
- Messages suivi
- Général

![capture d ecran 2015-09-24 a 16 23 15](https://cloud.githubusercontent.com/assets/3848536/10075481/490c2d08-62d6-11e5-8dd8-c50ffc91d600.png)

**Comment by mperrien** [comment]
Fixed
