### ISSUE TITLE
Dashboard Mes courses : btw 1200px & 780px : unsubscribe links are hidden

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#18]
http://stage.mooc.rue89.com/dashboard

![capture d ecran 2015-10-05 a 11 10 09](https://cloud.githubusercontent.com/assets/3848536/10276350/3733e644-6b4f-11e5-9d07-8775923a804b.png)

**Comment by fabienstreit** [comment]
solution proposée :
- agrandir le bloc blanc vers le bas en fontion de la quantité de contenu de la partie de droite
- cropper l'image de gauche (image en cover) pour qu'elle prenne toujours la totalité de l'espace sans s'anamorphoser

**Comment by mperrien** [comment]
Je n'ai pas ce problème en local et je ne peux pas accéder à cette page sur stage, parce que je ne peux plus m'inscrire à des cours (mon dashboard est vide).
Peux-tu m'envoyer tes identifiants stage par mail ?

**Comment by mperrien** [comment]
@fabienstreit Je ne t'ai pas mentionné dans mon commentaire, tu ne l'as peut-être pas vu.
Si tu m'envoies ton identifiant de connexion à stage, je peux régler ça demain première heure.

**Comment by fabienstreit** [comment]
je t'ai envoyé mes identifiants par mail.

**Comment by mperrien** [comment]
Fixed.
