### ISSUE TITLE
Unsubscribe popup : font is black on red button (should be white)

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#19]
http://stage.mooc.rue89.com/dashboard

![capture d ecran 2015-10-05 a 11 11 34](https://cloud.githubusercontent.com/assets/3848536/10276402/78054c9e-6b4f-11e5-8919-6052b9cc7857.png)

**Comment by fabienstreit** [comment]
![capture d ecran 2015-10-05 a 11 12 47](https://cloud.githubusercontent.com/assets/3848536/10276426/9254034c-6b4f-11e5-9745-56abb5ef6571.png)

**Comment by mperrien** [comment]
Fixed.
