### ISSUE TITLE
Course About : delete green cover on pictures

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#21]
![capture d ecran 2015-10-07 a 16 30 28](https://cloud.githubusercontent.com/assets/3848536/10339988/4f4cb93e-6d0e-11e5-9dac-3076a0e7f010.png)

**Comment by fabienstreit** [comment]
Hello Marc, je n'ai pas vu de retour de ta part sur ce point. Est-il en place ?

**Comment by mperrien** [comment]
Fixed
