### ISSUE TITLE
COURSES : ABOUT : add curser:pointer and hover:underline on accordion style menu

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#24]
![capture d ecran 2015-10-12 a 16 48 31](https://cloud.githubusercontent.com/assets/3848536/10430341/f1f5e950-70fe-11e5-9152-a11e5c84f816.png)

**Comment by mperrien** [comment]
Je laisse ouvert et je ferai des ajustements suite à la prise en compte du nouveau markup proposé.
