### ISSUE TITLE
REGISTER FORM : changer le lien sur "j'accepte les conditions d'utilisation" 

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#25]
mettre ce lien : 
http://mooc.rue89.com/tos
![capture d ecran 2015-10-14 a 12 02 51](https://cloud.githubusercontent.com/assets/3848536/10480184/01adcd0c-7269-11e5-9220-7d988decb7dd.png)

**Comment by mperrien** [comment]
I think this is out of my scope (out of the folder themes/rue89), maybe @smarnach can confirm that.

**Comment by smarnach** [comment]
@mperrien Yep, I think this is easier to change by updating the translation.

CC @antoviaque

**Comment by antoviaque** [comment]
@smarnach I don't think the link would be translated, no? That would require a platform change, which would not be easy to get upstream. 

It would be better to avoid a platform change here - the link currently points to http://mooc.rue89.com/honor which correctly contains both the charte and language indicating acceptance of the CGU with links to it. What is wrong with the current approach?

**Comment by fabienstreit** [comment]
@antoviaque : Indeed it seems like it would be fine legaly speaking. I'll double check that with Valerie.

**Comment by antoviaque** [comment]
@fabienstreit Thanks!
