### ISSUE TITLE
COURSE ABOUT : VIDEO BUTTON : center triangle into circle

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#26]
![bouton video](https://cloud.githubusercontent.com/assets/3848536/10510437/519f6cd8-7333-11e5-9509-33a8d7f9d337.JPG)

**Comment by mperrien** [comment]
@fabienstreit C'est bien sur http://mooc.rue89.com/courses/course-v1:Rue89+Rue89+2015_4/about ? Avec quel navigateur ?

**Comment by fabienstreit** [comment]
ni avec chrome mac ni avec firefox mac... possiblement internet explorer... je viens de lui demander.

**Comment by mperrien** [comment]
Problème sur PC. Corrigé en utilsant FontAwesome plutôt que le caractère ▶ qui n'est visiblement pas très consistant...
