### ISSUE TITLE
course list : l'image vignette n'est pas redimensionnée en prod

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#28]
C'est un problème étonnant, qui ne semble se produire qu'en prod. Mais l'image est cropée au lieu d'être redimensionnée. cf. cette conversation sur basecamp pour plus de détails : 
https://basecamp.com/1719607/projects/9120055/messages/50015190#comment_346044751

peux-tu regarder ?

**Comment by fabienstreit** [comment]
fyi : ça concerne la HP non connectée.

**Comment by fabienstreit** [comment]
En fait il semble que ce soit le mm soucis en stage, sauf que les images étaient uploadée qu format vignettes puis redimensionnées dans la fiche. Il faudrait qu'on puisse faire le contraire pour ne pas se retrouver avec des images pixelisées dans la fiche. Donc redimensionner dans la liste à 400x220 en croppant au centre si jamais le ratio n'est pas le bon.
ok pour toi ?

**Comment by mperrien** [comment]
Fixed.
Commited.
Pull request pinged to mtyaka
