### ISSUE TITLE
Course lists : btween 1190px & 755px width, long titles and course dates goes over the bouton "voir le cours"

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#3]
exemple : http://stage.mooc.rue89.com/dashboard

![capture d ecran 2015-09-18 a 17 22 02](https://cloud.githubusercontent.com/assets/3848536/10047619/47ac2566-620f-11e5-9a6d-62047b0ad278.png)
![capture d ecran 2015-09-18 a 17 22 14](https://cloud.githubusercontent.com/assets/3848536/10047644/5d08c64e-620f-11e5-86dc-2a9ea84fd8f0.png)

**Comment by mperrien** [comment]
Fixed
