### ISSUE TITLE
HP déconnecté : problèmes sur les blocs contenus

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#30]
- l'image est anamorphosée
- le titre passe sur plusieurs lignes au lieu de prendre toute la largeur du bloc
- les marges latterrales ne sont pas conformes entre le header et les blocs de contenus

![capture d ecran 2015-10-26 a 15 23 15](https://cloud.githubusercontent.com/assets/3848536/10730955/464d1ae2-7bf3-11e5-8eb6-59ff265179f1.png)

**Comment by mperrien** [comment]
OK. Réglé.
