### ISSUE TITLE
Course About : déconnecté : problèmes de mise en page

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#31]
- l'image est très anamorphosée
- les marges droites et gauches sont beaucoup trop larges et devraient être identiques au marges du header
- header : le bouton "connexion" est éloigné du logo

![capture d ecran 2015-10-26 a 15 22 27](https://cloud.githubusercontent.com/assets/3848536/10731038/aac3d18c-7bf3-11e5-9127-8a51b74fa267.png)
![capture d ecran 2015-10-26 a 15 22 35](https://cloud.githubusercontent.com/assets/3848536/10731039/b19c1582-7bf3-11e5-8dc0-d30fd16ef5cc.png)

**Comment by mperrien** [comment]
Corrigé.
