### ISSUE TITLE
Font color on buttons : Should be white on Red / Black on Green and Grey

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#4]
http://share.upian.net/-Rue89-Mooc/Guidelines_integration/150720_Rue89_Mooc_Guidelines_06-Tailles_etiquettes_categories_et_boutons.png

cf. 
http://www.awesomescreenshot.com/image/602912/cc453fa318a5bcab7eface7cf2d02e5a
http://www.awesomescreenshot.com/image/602918/6b337cbfbd3d4b2f62a42f91475416ff
http://www.awesomescreenshot.com/image/602928/b9200f3428e50807b71b2306f88913d2

**Comment by mperrien** [comment]
Fixed
