### ISSUE TITLE
Courses/About : Hide the title of the course in the header

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#5]
Hide the title here :
http://rue89-theme2.sandbox.opencraft.com/courses/course-v1:TestX+TST-2+now/about

But keep it here : 
http://rue89-theme2.sandbox.opencraft.com/courses/course-v1:TestX+TST-2+now/info

I know it can't be hiddenin CSS only on the ABOUT page (whithout beeing hidden on the connected courses pages). 

Can it be done directly in the markup ?

**Comment by antoviaque** [comment]
@fabienstreit @mperrien What about:

```
body:not(.view-incourse) header.global.slim .course-header {
    visibility: hidden;
}
```

**Comment by mperrien** [comment]
Works great, thanks @antoviaque 
Fixed
