### ISSUE TITLE
Unsubscribe to a course : popup : use the title instead of the reference of the course

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#6]
![2](https://cloud.githubusercontent.com/assets/3848536/10073470/70790274-62c9-11e5-982f-6a1329fcfaa1.JPG)

**Comment by antoviaque** [comment]
@fabienstreit @mperrien We could prepare a code change for this - upstream might accept to add the title next to the reference here, and we could make the change to the dom in a way that makes it easy to hide the reference via CSS in the theme. Would that work for you?

**Comment by fabienstreit** [comment]
yeah sounds good to me.

**Comment by mtyaka** [comment]
Updates from https://github.com/edx/edx-platform/pull/10007 were deployed to the staging instance.

**Comment by mtyaka** [comment]
https://github.com/rue89-tech/edx-theme/pull/17

**Comment by antoviaque** [comment]
@mperrien Just reassigning to you so you can verify the change on your side - this should now be done.

**Comment by fabienstreit** [comment]
I confirme that it's done. Just waiting for a smal change on the button style here https://github.com/rue89-tech/edx-theme/issues/19

**Comment by antoviaque** [comment]
Perfect - thanks for the confirmation, closing this then.
