### ISSUE TITLE
Course/ABOUT : H1 style : minimize paddings to make it smaller

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#9]
http://www.awesomescreenshot.com/image/603595/444a1de41ab564366741949fb5ed3831

cf. maquettes : http://share.upian.net/-Rue89-Mooc/production-site/150703_rue89_mooc_charte1-01.png
vs : http://rue89-theme2.sandbox.opencraft.com/courses/course-v1:TestX+TST-1+now/about

**Comment by mperrien** [comment]
Fixed
